// Code generated by MockGen. DO NOT EDIT.
// Source: broozkan/postapi/internal/handlers (interfaces: PostServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "broozkan/postapi/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostServiceInterface is a mock of PostServiceInterface interface.
type MockPostServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceInterfaceMockRecorder
}

// MockPostServiceInterfaceMockRecorder is the mock recorder for MockPostServiceInterface.
type MockPostServiceInterfaceMockRecorder struct {
	mock *MockPostServiceInterface
}

// NewMockPostServiceInterface creates a new mock instance.
func NewMockPostServiceInterface(ctrl *gomock.Controller) *MockPostServiceInterface {
	mock := &MockPostServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPostServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostServiceInterface) EXPECT() *MockPostServiceInterfaceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostServiceInterface) CreatePost(arg0 context.Context, arg1 *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceInterfaceMockRecorder) CreatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostServiceInterface)(nil).CreatePost), arg0, arg1)
}
