appname: "post-api-dev"
server:
  port: ":3000"
adsEnabled: true
postLengthAdPositionMap:
  3: 1
  17: 16
itemPerPage:    27
authorPrefix:   "t2_"
authorIDLength: 8
couchbase:
  url: "couchbase://couchbase"
  username: admin
  password: password
  buckets:
    - name: "post"
      scopes:
        - name: ""
          collections:
            - name: "posts"
              createPrimaryIndex: true